# config.yaml
server:
  host: 192.168.1.196 #218.77.75.138
  port:  21 #20191
  username: ftpuser #admin
  password: code@2023 #"Hyga@_Hy110#110"

directories:
  local_watch: "D:/booster"  # 本地监听目录
  remote_destination: "/data3"  # FTP服务器目标目录

logging:
  level: "info"
  file: "logs/app.log"
  max_size_mb: 100    # 单个日志文件最大大小（MB）
  max_backups: 5      # 保留的旧日志文件数量
  max_age_days: 30    # 日志文件保留天数
  compress: true      # 是否压缩旧日志

upload:
  retry_attempts: 0
  retry_delay_seconds: 5
  max_file_size_mb: 1000  # 限制上传文件大小
  retry_queue_delay: 1h

file_filters:
  include_patterns:
#    - "*.txt"
#    - "*.log"
#    - "*.csv"
  exclude_patterns:
    - "temp*"
    - "*.tmp"

